name: Python Tests

on:
  push:
    branches: [ development, master ]
  pull_request:
    branches: [ development, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv venv .venv
        source .venv/bin/activate
        uv sync
    - name: Run tests
      run: |
        source .venv/bin/activate
        python -m pytest tests/ -v
